export const menuLabels = {
  dashboard: 'Trang chủ',
  users: 'Quản lý người dùng',
  roles: 'Vai trò',
  students: 'Quản lý học sinh',
  classes: 'Quản lý lớp học',
  enrollments: 'Phân lớp',
  transfer: 'Chuyển lớp',
  teachers: 'Quản lý giáo viên',
  teacherAssignments: 'Phân công giáo viên',
  scores: 'Tra cứu điểm',
  scoreEntry: 'Nhập bảng điểm',
  scoreChangeRequests: 'Yêu cầu sửa điểm',
  reports: 'Báo cáo',
  parameters: 'Quy định / Tham số',
  classReport: 'Báo cáo lớp chủ nhiệm',
  subjectReport: 'Báo cáo môn giảng dạy',
  myProfile: 'Hồ sơ cá nhân',
  myScores: 'Điểm của tôi',
  myAssignments: 'Phân công của tôi',
  auditLogs: 'Nhật ký hệ thống',
  conductAssessment: 'Đánh giá hạnh kiểm',
  conductReview: 'Duyệt hạnh kiểm',
  semesterFinalize: 'Chốt điểm học kỳ',
  yearEnd: 'Tổng kết năm học',
  timetable: 'Thời khóa biểu',
  myTimetable: 'TKB của tôi',
} as const;

export const appText = {
  appName: 'Quản lý học sinh',
  appSubtitle: 'SE104',
  systemName: 'Hệ thống Quản lý Học sinh',
  loginTitle: 'Đăng nhập',
  loginSubtitle: 'Đăng nhập để tiếp tục',
  username: 'Tên đăng nhập',
  usernamePlaceholder: 'Nhập tên đăng nhập',
  password: 'Mật khẩu',
  passwordPlaceholder: 'Nhập mật khẩu',
  loggingIn: 'Đang đăng nhập...',
  enterSystem: 'Vào hệ thống',
  logout: 'Đăng xuất',
  loadingSession: 'Đang tải phiên đăng nhập...',
  dashboardGreeting: 'Chọn nhanh chức năng theo vai trò hiện tại.',
} as const;

export const commonLabels = {
  actions: 'Thao tác',
  allStatuses: 'Tất cả trạng thái',
  apply: 'Áp dụng',
  cancel: 'Hủy',
  create: 'Thêm mới',
  delete: 'Xóa',
  detail: 'Chi tiết',
  edit: 'Chỉnh sửa',
  error: 'Đã xảy ra lỗi',
  loading: 'Đang tải dữ liệu...',
  noData: 'Chưa có dữ liệu',
  reset: 'Đặt lại',
  save: 'Lưu',
  saving: 'Đang lưu...',
  search: 'Tìm kiếm',
  select: 'Chọn',
  submit: 'Gửi',
  status: 'Trạng thái',
  update: 'Cập nhật',
} as const;
